version: '3'
# replace 192.168.1.1 to real server ip
services:
  elasticsearch:
    image: docker.nju.edu.cn/library/elasticsearch:8.8.1
    container_name: elasticsearch-server
    restart: always
    ports:
      - "55005:9200"
      - "55006:9300"
    environment:
      - ELASTIC_PASSWORD=superadmin
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    # mem_limit: 1g
    volumes:
      - /data/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - /data/docker/elasticsearch/logs:/usr/share/elasticsearch/logs
    deploy:
      resources:
        limits:
          memory: 14G
          cpus: "8.00"
  logstash-api-analytics:
    image: docker.nju.edu.cn/library/logstash:8.8.1
    container_name: logstash-api-analytics-cluster-server
    restart: always
    environment:
      - ELASTICSEARCH_USERNAME=logstash_system
      - ELASTICSEARCH_PASSWORD=logstash_admin
      - ELASTICSEARCH_URL=http://192.168.1.1:55005
      - NODE_NAME=logstash-server
      - XPACK_MONITORING_ENABLED=true
      - PATH_CONFIG=/usr/share/logstash/config.d
    volumes:
      - /data/docker/logstash-api-analytics/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /data/docker/logstash-api-analytics/conf.d:/usr/share/logstash/config.d
      - /data/docker/logstash-api-analytics/csv:/usr/share/logstash/csv
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 14G
          cpus: "8.00"
  logstash-event-tracker:
    image: docker.nju.edu.cn/library/logstash:8.8.1
    container_name: logstash-event-tracker-cluster-server
    restart: always
    environment:
      - ELASTICSEARCH_USERNAME=logstash_system
      - ELASTICSEARCH_PASSWORD=logstash_admin
      - ELASTICSEARCH_URL=http://192.168.1.1:55005
      - NODE_NAME=logstash-server
      - XPACK_MONITORING_ENABLED=true
      - PATH_CONFIG=/usr/share/logstash/config.d
    volumes:
      - /data/docker/logstash-event-tracker/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /data/docker/logstash-event-tracker/conf.d:/usr/share/logstash/config.d
      - /data/docker/logstash-event-tracker/csv:/usr/share/logstash/csv
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 14G
          cpus: "8.00"
  kibana:
    image: docker.nju.edu.cn/library/kibana:8.8.1
    container_name: kibana-server
    ports:
      - "55007:5601"
    restart: always
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana_admin
      - ELASTICSEARCH_URL=http://192.168.1.1:55005
      - SERVER_NAME=kibana-server
      - XPACK_SECURITY_ENABLED=true
      - PATH_DATA=/usr/share/kibana/data
    volumes:
      - /data/docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /data/docker/kibana/data:/usr/share/kibana/data
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 14G
          cpus: "8.00"