version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch-server
    restart: always
    ports:
      - "55005:9200"
      - "55006:9300"
    environment:
      - ELASTIC_PASSWORD=superadmin
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    container_name: logstash-server
    restart: always
    environment:
      - ELASTICSEARCH_USERNAME=logstash_system
      - ELASTICSEARCH_PASSWORD=logstash_admin
      - ELASTICSEARCH_URL=http://192.168.2.250:55005
      - NODE_NAME=logstash-server
      - XPACK_MONITORING_ENABLED=true
      - PATH_CONFIG=/usr/share/logstash/config.d
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/conf.d:/usr/share/logstash/config.d
      - ./logstash/csv:/usr/share/logstash/csv
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana-server
    ports:
      - "55007:5601"
    restart: always
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana_admin
      - ELASTICSEARCH_URL=http://192.168.2.250:55005
      - SERVER_NAME=kibana-server
      - XPACK_SECURITY_ENABLED=true
      - PATH_DATA=/usr/share/kibana/data
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/data:/usr/share/kibana/data
    links:
      - elasticsearch
    depends_on:
      - elasticsearch